import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import dotenv from "dotenv";
import { autoResolveCompanyLogo } from "../src/utils/companyLogoResolver";

dotenv.config();

const adapter = new PrismaPg(process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter });

function simpleHash(str: string): string {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  let hash2 = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    hash2 ^= str.charCodeAt(i);
    hash2 = Math.imul(hash2, 0x01000193);
  }
  return (hash >>> 0).toString(36) + (hash2 >>> 0).toString(36);
}

function generateFingerprint(company: string, title: string, location: string, applyUrl: string): string {
  const c = company.toLowerCase().trim().replace(/[^a-z0-9]/g, "");
  const t = title.toLowerCase().trim().replace(/[^a-z0-9]/g, "");
  const l = location.toLowerCase().trim().replace(/[^a-z0-9]/g, "");
  const u = applyUrl.toLowerCase().trim();
  return simpleHash(`${c}|${t}|${l}|${u}`);
}

const SOURCES = [
  { name: "linkedin", displayName: "LinkedIn", schedule: "6h" },
  { name: "naukri", displayName: "Naukri", schedule: "daily" },
  { name: "indeed", displayName: "Indeed", schedule: "6h" },
  { name: "internshala", displayName: "Internshala", schedule: "daily" },
  { name: "remoteok", displayName: "RemoteOK", schedule: "6h" },
  { name: "wellfound", displayName: "Wellfound", schedule: "daily" },
  { name: "foundit", displayName: "Foundit", schedule: "daily" },
];

const COMPANIES = [
  { name: "Google", slug: "google", industry: "Technology", companySize: "10000+", website: "https://google.com", location: "Bangalore, India", techStack: ["Python", "C++", "Java", "Go", "TensorFlow", "Kubernetes", "GCP"], difficultyLevel: "hard", description: "Google's mission is to organize the world's information and make it universally accessible and useful." },
  { name: "Microsoft", slug: "microsoft", industry: "Technology", companySize: "10000+", website: "https://microsoft.com", location: "Hyderabad, India", techStack: ["C#", ".NET", "TypeScript", "Azure", "React", "Python"], difficultyLevel: "hard", description: "Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge." },
  { name: "Amazon", slug: "amazon", industry: "E-commerce & Cloud", companySize: "10000+", website: "https://amazon.jobs", location: "Bangalore, India", techStack: ["Java", "AWS", "Python", "C++", "DynamoDB", "React"], difficultyLevel: "hard", description: "Amazon is guided by four principles: customer obsession, passion for invention, commitment to operational excellence, and long-term thinking." },
  { name: "Meta", slug: "meta", industry: "Social Media & Tech", companySize: "10000+", website: "https://metacareers.com", location: "Gurgaon, India", techStack: ["React", "React Native", "PyTorch", "Python", "GraphQL", "C++"], difficultyLevel: "hard", description: "Meta builds technologies that help people connect, find communities, and grow businesses." },
  { name: "Swiggy", slug: "swiggy", industry: "FoodTech & Delivery", companySize: "5001-10000", website: "https://swiggy.com", location: "Bangalore, India", techStack: ["Go", "Java", "React", "Kotlin", "AWS", "Kafka", "Redis"], difficultyLevel: "medium", description: "Swiggy is India's leading on-demand convenience platform." },
  { name: "Zomato", slug: "zomato", industry: "FoodTech", companySize: "5001-10000", website: "https://zomato.com", location: "Gurgaon, India", techStack: ["Node.js", "React", "Python", "Go", "PostgreSQL", "AWS"], difficultyLevel: "medium", description: "Zomato's mission is better food for more people." },
  { name: "Razorpay", slug: "razorpay", industry: "FinTech & Payments", companySize: "1001-5000", website: "https://razorpay.com", location: "Bangalore, India", techStack: ["Go", "PHP", "Node.js", "React", "AWS", "MySQL", "Kafka"], difficultyLevel: "medium", description: "Razorpay is India's first full-stack financial services company." },
  { name: "Flipkart", slug: "flipkart", industry: "E-commerce", companySize: "10000+", website: "https://flipkartcareers.com", location: "Bangalore, India", techStack: ["Java", "Scala", "React", "Python", "Kafka", "HBase", "GCP"], difficultyLevel: "hard", description: "Flipkart is India's leading e-commerce marketplace." },
  { name: "Uber", slug: "uber", industry: "Mobility & Tech", companySize: "10000+", website: "https://uber.com/careers", location: "Bangalore, India", techStack: ["Go", "Java", "Python", "React", "Kafka", "Cassandra"], difficultyLevel: "hard", description: "Uber's technology helps move people and items efficiently across cities globally." },
  { name: "Atlassian", slug: "atlassian", industry: "Developer Tools", companySize: "5001-10000", website: "https://atlassian.com", location: "Bengaluru, India", techStack: ["Java", "React", "TypeScript", "AWS", "GraphQL", "Kotlin"], difficultyLevel: "hard", description: "Atlassian builds software for team collaboration, development, and project management." },
  { name: "Vercel", slug: "vercel", industry: "Cloud Platform", companySize: "201-500", website: "https://vercel.com", location: "Remote", techStack: ["Next.js", "TypeScript", "React", "Node.js", "Go", "Rust"], difficultyLevel: "hard", description: "Vercel is the frontend cloud platform for developer teams." },
  { name: "Stripe", slug: "stripe", industry: "FinTech", companySize: "5001-10000", website: "https://stripe.com", location: "Remote / Bangalore", techStack: ["Ruby", "Go", "Java", "React", "TypeScript", "AWS"], difficultyLevel: "hard", description: "Stripe is a financial infrastructure platform for businesses." },
  { name: "NVIDIA", slug: "nvidia", industry: "Hardware & AI Software", companySize: "10000+", website: "https://nvidia.com", location: "Pune, India", techStack: ["CUDA", "C++", "Python", "PyTorch", "TensorRT", "Linux"], difficultyLevel: "hard", description: "NVIDIA is the pioneer of GPU-accelerated computing and AI hardware infrastructure." },
  { name: "OpenAI", slug: "openai", industry: "Artificial Intelligence", companySize: "501-1000", website: "https://openai.com", location: "Remote / USA", techStack: ["Python", "PyTorch", "CUDA", "Kubernetes", "TypeScript", "Rust"], difficultyLevel: "hard", description: "OpenAI's mission is to ensure that artificial general intelligence benefits all of humanity." },
];

const JOBS_DATA = [
  {
    title: "Senior Full Stack Engineer (Next.js & Node.js)",
    company: "Vercel",
    logoUrl: "https://assets.vercel.com/image/upload/front/favicon/vercel/180x180.png",
    location: "Remote",
    country: "Global",
    state: "Remote",
    city: "Remote",
    description: "Join Vercel's core Product Engineering team to build modern web developer tools, dashboard experiences, and serverless edge runtime features. You will work closely with Next.js core engineers to elevate web development standards globally.",
    salaryMin: 2800000,
    salaryMax: 4500000,
    experienceMin: 4,
    experienceMax: 8,
    employmentType: "Full-Time",
    workMode: "Remote",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "TailwindCSS", "GraphQL", "AWS"],
    requirements: ["4+ years of professional full-stack development experience", "Deep expertise in Next.js, React, and TypeScript", "Strong understanding of web performance, SSR, ISR, and Edge network computing", "Proven track record building complex SaaS user interfaces"],
    responsibilities: ["Architect, develop, and maintain high-performance frontend interfaces", "Design robust Node.js and Serverless microservices", "Collaborate with product managers, UX designers, and platform engineers", "Mentor junior team members and maintain code quality"],
    benefits: ["100% Remote flexibility", "Competitive stock options (RSUs)", "Unlimited paid time off (PTO)", "Home office setup stipend & learning allowance"],
    education: "Bachelor's in Computer Science or equivalent practical experience",
    industry: "Cloud Platform",
    companySize: "201-500",
    applyUrl: "https://vercel.com/careers/fullstack-engineer",
    sourceUrl: "https://vercel.com/careers",
    source: "wellfound",
    isFeatured: true,
  },
  {
    title: "AI / Machine Learning Engineer (LLMs & Generative AI)",
    company: "Google",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Google Cloud AI team is hiring Senior ML Engineers to scale Gemini LLM applications for enterprise customers. You will design, fine-tune, evaluate, and deploy state-of-the-art transformer models into mission-critical cloud services.",
    salaryMin: 3200000,
    salaryMax: 6000000,
    experienceMin: 3,
    experienceMax: 7,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Python", "PyTorch", "TensorFlow", "LLM", "LangChain", "GCP", "Kubernetes", "C++"],
    requirements: ["MS or PhD in Computer Science, Machine Learning, or AI", "Experience fine-tuning and deploying large language models (LLMs)", "Proficiency in PyTorch or JAX and distributed GPU training", "Strong background in Data Structures, Algorithms, and Software Engineering"],
    responsibilities: ["Build scalable model training and serving pipelines on GCP Vertex AI", "Fine-tune foundation models for specialized domain reasoning", "Benchmark model accuracy, latency, and memory footprints", "Collaborate with research scientists to convert breakthroughs into products"],
    benefits: ["Top-tier compensation and annual equity grants", "Comprehensive health coverage for family", "On-site gourmet cafeterias and wellness centers", "Generous education sponsorship"],
    education: "Master's or PhD in CS/AI",
    industry: "Technology",
    companySize: "10000+",
    applyUrl: "https://careers.google.com/jobs/results/ai-ml-engineer",
    sourceUrl: "https://careers.google.com",
    source: "linkedin",
    isFeatured: true,
  },
  {
    title: "Backend Engineer - Distributed Systems & Microservices",
    company: "Amazon",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Amazon Web Services (AWS) DynamoDB engineering team is looking for Backend Engineers to solve high-throughput, ultra-low latency distributed systems challenges handling billions of requests daily.",
    salaryMin: 2400000,
    salaryMax: 4200000,
    experienceMin: 2,
    experienceMax: 6,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Java", "Go", "AWS", "Distributed Systems", "DynamoDB", "Kafka", "Docker", "SQL"],
    requirements: ["2+ years experience building distributed, fault-tolerant backend systems", "Solid grasp of computer science fundamentals (data structures, algorithms, OS)", "Hands-on experience with Java, C++, or Go", "Familiarity with cloud-native architectures"],
    responsibilities: ["Design and implement scalable distributed services for AWS core infrastructure", "Optimize database query paths for sub-millisecond latencies", "Participate in on-call rotation and system reliability engineering", "Write automated unit, integration, and stress tests"],
    benefits: ["Amazon Stock Units (RSUs)", "Comprehensive medical insurance", "Relocation assistance to Bangalore", "Flexible work schedule"],
    education: "Bachelor's in CS / IT / ECE",
    industry: "E-commerce & Cloud",
    companySize: "10000+",
    applyUrl: "https://amazon.jobs/en/jobs/backend-engineer-aws",
    sourceUrl: "https://amazon.jobs",
    source: "naukri",
    isFeatured: true,
  },
  {
    title: "Frontend Lead Engineer (React & TypeScript)",
    company: "Razorpay",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Razorpay is seeking a Frontend Lead Engineer to lead the Checkout & Payment Gateway frontend team. You will be responsible for building seamless payment flows used by millions of merchants and consumers daily across India.",
    salaryMin: 3000000,
    salaryMax: 5000000,
    experienceMin: 5,
    experienceMax: 10,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["React", "TypeScript", "Redux", "Webpack", "TailwindCSS", "Jest", "Web Vitals"],
    requirements: ["5+ years experience in frontend engineering with focus on React & JS performance", "Deep understanding of browser rendering, security (CORS, CSP), and state management", "Experience leading small technical teams and code reviews", "Passionate about web accessibility (WCAG) and micro-frontend architecture"],
    responsibilities: ["Lead design and implementation of Razorpay Checkout JavaScript SDK", "Ensure 99.99% uptime and lightning-fast load times for payment modal", "Drive frontend architecture standards, component libraries, and testing suites", "Work with product managers to launch new payment methods"],
    benefits: ["Esops liquidity options", "Medical insurance including mental health support", "Work-from-home setup allowance", "Flexi-benefits basket"],
    education: "Bachelor's degree in CS/Engineering",
    industry: "FinTech & Payments",
    companySize: "1001-5000",
    applyUrl: "https://razorpay.com/jobs/frontend-lead",
    sourceUrl: "https://razorpay.com/jobs",
    source: "linkedin",
    isFeatured: true,
  },
  {
    title: "DevOps / SRE Engineer (Kubernetes & Infrastructure)",
    company: "Swiggy",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Swiggy Infrastructure & Reliability team is hiring DevOps Engineers to manage multi-cloud Kubernetes clusters handling massive peak order volumes during food delivery hours.",
    salaryMin: 2200000,
    salaryMax: 3800000,
    experienceMin: 3,
    experienceMax: 7,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Kubernetes", "Docker", "Terraform", "AWS", "Ansible", "Prometheus", "Grafana", "Python", "Bash"],
    requirements: ["3+ years in DevOps / SRE roles managing production cloud infrastructure", "Strong expertise with AWS, Kubernetes (EKS), Terraform, and CI/CD pipelines", "Proficiency in scripting (Python, Go, or Bash)", "Experience with monitoring tools like Prometheus, Grafana, Datadog"],
    responsibilities: ["Maintain and automate Kubernetes deployments for 500+ microservices", "Implement auto-scaling policies to handle order surges", "Improve incident response workflows and post-mortem automation", "Optimize cloud spending and infrastructure efficiency"],
    benefits: ["Swiggy Money allowance for meals", "Stock Options (ESOPs)", "Full healthcare coverage", "Flexible working arrangements"],
    education: "B.Tech/BE in CS/IT/ECE",
    industry: "FoodTech & Delivery",
    companySize: "5001-10000",
    applyUrl: "https://swiggy.com/careers/devops-engineer",
    sourceUrl: "https://swiggy.com/careers",
    source: "indeed",
    isFeatured: false,
  },
  {
    title: "Data Scientist - Personalization & Recommendation Engine",
    company: "Zomato",
    location: "Gurgaon, Haryana, India",
    country: "India",
    state: "Haryana",
    city: "Gurgaon",
    description: "Join Zomato's Data Science team to build real-time recommendation algorithms that personalize home feeds, restaurant discovery, and dish suggestions for over 50 million active foodies.",
    salaryMin: 2500000,
    salaryMax: 4500000,
    experienceMin: 3,
    experienceMax: 6,
    employmentType: "Full-Time",
    workMode: "Onsite",
    skills: ["Python", "SQL", "Scikit-Learn", "Pandas", "PyTorch", "Spark", "A/B Testing", "RecSys"],
    requirements: ["Strong background in Statistics, Machine Learning, and Recommendation Systems", "Hands-on experience with Collaborative Filtering, Matrix Factorization, and Deep Learning RecSys", "Fluent in Python, SQL, and PySpark", "Track record of running controlled A/B tests at scale"],
    responsibilities: ["Develop and deploy end-to-end recommendation models for the main Zomato app", "Analyze user interaction graphs to improve restaurant matching accuracy", "Collaborate with product and engineering teams to deploy real-time inference models", "Measure business ROI via continuous experimentation"],
    benefits: ["Free food at office cafes", "Performance bonuses and stock grants", "Comprehensive health insurance", "Generous parental leaves"],
    education: "Master's in Data Science, Statistics, Mathematics, or CS",
    industry: "FoodTech",
    companySize: "5001-10000",
    applyUrl: "https://zomato.com/careers/data-scientist",
    sourceUrl: "https://zomato.com/careers",
    source: "naukri",
    isFeatured: false,
  },
  {
    title: "Software Engineer - iOS / Swift",
    company: "Uber",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Uber Mobility mobile team is seeking experienced iOS Engineers to craft buttery smooth rider and driver mobile experiences powering millions of trips daily across the globe.",
    salaryMin: 2600000,
    salaryMax: 4800000,
    experienceMin: 3,
    experienceMax: 7,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Swift", "iOS", "UIKit", "Combine", "CoreData", "Git", "XCTest", "REST API"],
    requirements: ["3+ years of native iOS app development experience using Swift", "Strong knowledge of iOS architecture patterns (RIBs, MVVM, VIPER)", "Deep understanding of memory management, multi-threading, and UI responsiveness", "Experience publishing popular iOS apps to App Store"],
    responsibilities: ["Develop features for the core Uber Rider and Driver iOS applications", "Optimize app startup times, memory footprints, and frame rates", "Write comprehensive unit and UI automation tests", "Collaborate with product designers for pixel-perfect iOS UI"],
    benefits: ["Uber credits for rides & food", "High-value RSUs", "Comprehensive wellness program", "Modern tech stack and MacBook Pro setup"],
    education: "B.Tech/BE in CS or IT",
    industry: "Mobility & Tech",
    companySize: "10000+",
    applyUrl: "https://uber.com/careers/ios-engineer",
    sourceUrl: "https://uber.com/careers",
    source: "linkedin",
    isFeatured: false,
  },
  {
    title: "Junior Java Developer / Freshers Welcome",
    company: "TCS",
    location: "Pune, Maharashtra, India",
    country: "India",
    state: "Maharashtra",
    city: "Pune",
    description: "Tata Consultancy Services (TCS) is hiring entry-level and junior Java software engineers for enterprise digital transformation projects across Banking, Financial Services, and Retail sectors.",
    salaryMin: 450000,
    salaryMax: 900000,
    experienceMin: 0,
    experienceMax: 2,
    employmentType: "Full-Time",
    workMode: "Onsite",
    skills: ["Java", "Spring Boot", "SQL", "HTML", "CSS", "Git", "Hibernate"],
    requirements: ["B.Tech / B.E. / M.Tech / MCA (2023-2026 Batch)", "Good grasp of Core Java, OOP concepts, and SQL relational databases", "Basic knowledge of Spring Boot or Hibernate is a plus", "Excellent problem solving and communication skills"],
    responsibilities: ["Develop clean, readable Java code following enterprise standards", "Assist in database schema design and writing SQL queries", "Fix bugs and write unit tests using JUnit", "Participate in daily Agile standup meetings"],
    benefits: ["Initial onboarding & training program", "Health insurance for self & dependents", "Internal career growth programs (Elevate)", "Corporate discounts"],
    education: "B.Tech / BE / MCA / M.Sc in CS or IT",
    industry: "IT Services",
    companySize: "10000+",
    applyUrl: "https://tcs.com/careers/junior-java-developer",
    sourceUrl: "https://naukri.com",
    source: "naukri",
    isFeatured: false,
  },
  {
    title: "Frontend Developer Internship (React & Web3)",
    company: "RemoteOK",
    location: "Remote",
    country: "Global",
    state: "Remote",
    city: "Remote",
    description: "RemoteOK client ecosystem is looking for an enthusiastic Frontend Engineering Intern to build modern decentralized application (dApp) user interfaces, wallet integration screens, and interactive crypto dashboards.",
    salaryMin: 600000,
    salaryMax: 1200000,
    experienceMin: 0,
    experienceMax: 1,
    employmentType: "Internship",
    workMode: "Remote",
    skills: ["React", "JavaScript", "TypeScript", "TailwindCSS", "Ethers.js", "Web3.js", "HTML", "CSS"],
    requirements: ["Proficiency in React, HTML5, CSS3, and JavaScript (ES6+)", "Hands-on side projects demonstrating Web3 / dApp UI development", "Comfortable working autonomously in a remote team environment", "Basic understanding of smart contract interactions via Ethers.js"],
    responsibilities: ["Build responsive web pages based on Figma wireframes", "Connect frontend components to Web3 wallets (MetaMask, Phantom)", "Fix visual bugs and refine micro-animations using Framer Motion", "Participate in weekly async code review sessions"],
    benefits: ["USD stipend ($500 - $1000 / month)", "100% Remote flexibility", "Mentorship from senior Web3 engineers", "Pre-Placement Offer (PPO) based on performance"],
    education: "Pursuing or completed Bachelor's in CS / IT",
    industry: "Technology",
    companySize: "11-50",
    applyUrl: "https://remoteok.com/remote-jobs/frontend-intern",
    sourceUrl: "https://remoteok.com",
    source: "remoteok",
    isFeatured: false,
  },
  {
    title: "Cybersecurity Analyst & Penetration Tester",
    company: "Microsoft",
    location: "Hyderabad, Telangana, India",
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    description: "Microsoft Security Response Center (MSRC) is seeking a Penetration Tester & Security Analyst to audit Azure cloud services, find zero-day vulnerabilities, and fortify enterprise security postures.",
    salaryMin: 2800000,
    salaryMax: 4800000,
    experienceMin: 3,
    experienceMax: 8,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Cybersecurity", "Penetration Testing", "Python", "Linux", "Network Security", "OWASP", "Burp Suite", "Azure"],
    requirements: ["3+ years experience in ethical hacking, penetration testing, or red teaming", "Industry certifications such as OSCP, CEH, or CISSP preferred", "Expertise with OWASP Top 10, threat modeling, and web/API vulnerability analysis", "Scripting experience in Python, PowerShell, or Bash for exploit automation"],
    responsibilities: ["Perform offensive security assessments on Azure cloud infrastructure", "Document vulnerabilities and provide remediation recommendations to product teams", "Conduct code reviews for security flaws", "Participate in bug bounty triaging and threat intelligence sharing"],
    benefits: ["Microsoft Stock Units", "Relocation support", "Comprehensive medical & life insurance", "Certification & conference sponsorship"],
    education: "Bachelor's degree in CS, Cybersecurity, or related technical field",
    industry: "Technology",
    companySize: "10000+",
    applyUrl: "https://careers.microsoft.com/jobs/security-analyst",
    sourceUrl: "https://careers.microsoft.com",
    source: "linkedin",
    isFeatured: false,
  },
  {
    title: "Product Manager - AI Platform & Developer Tools",
    company: "Atlassian",
    location: "Bengaluru, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    description: "Atlassian is looking for a Product Manager to lead the integration of Generative AI capabilities (Rovo) across Jira, Confluence, and Bitbucket. You will drive product strategy, roadmap execution, and user experience.",
    salaryMin: 3500000,
    salaryMax: 5500000,
    experienceMin: 4,
    experienceMax: 8,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Product Management", "Agile", "Jira", "AI", "UX", "Data Analysis", "SQL", "Strategy"],
    requirements: ["4+ years experience in Technical Product Management for B2B SaaS or Developer Tools", "Strong understanding of Generative AI technologies, developer workflows, and API products", "Demonstrated ability to define product vision, telemetry metrics, and user stories", "Excellent written and verbal executive presentation skills"],
    responsibilities: ["Define product requirements and backlog for AI-powered assistant features", "Conduct customer discovery interviews with software developers and IT leaders", "Partner with engineering and UX design teams to ship features on timeline", "Track retention, activation, and feature adoption metrics"],
    benefits: ["Flexible remote-first work policy", "Generous stock grants (RSUs)", "Annual learning stipend of $2,000", "Top-tier medical coverage"],
    education: "Bachelor's degree in CS/Engineering or MBA",
    industry: "Developer Tools",
    companySize: "5001-10000",
    applyUrl: "https://atlassian.com/careers/product-manager-ai",
    sourceUrl: "https://atlassian.com/careers",
    source: "linkedin",
    isFeatured: true,
  },
  {
    title: "Deep Learning Compiler & GPU Infrastructure Engineer",
    company: "NVIDIA",
    location: "Pune, Maharashtra, India",
    country: "India",
    state: "Maharashtra",
    city: "Pune",
    description: "NVIDIA TensorRT team is hiring Deep Learning Compiler Engineers to optimize neural network inference on next-generation Blackwell and Hopper GPU microarchitectures.",
    salaryMin: 3500000,
    salaryMax: 6500000,
    experienceMin: 4,
    experienceMax: 9,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["C++", "CUDA", "Python", "PyTorch", "TensorRT", "Compilers", "LLVM", "Linux"],
    requirements: ["Strong background in C++17/20, CUDA programming, and GPU architectures", "Experience with compiler frameworks (LLVM, MLIR) or deep learning frameworks (PyTorch/TensorFlow)", "Deep understanding of memory hierarchy, SIMD, and kernel optimization", "MS/PhD in Computer Science or Electrical Engineering"],
    responsibilities: ["Implement graph optimizations and code generation in TensorRT compiler", "Optimize LLM inference throughput (FP8/INT4 quantization, FlashAttention)", "Benchmark kernel performance on latest NVIDIA GPUs", "Collaborate with AI research teams worldwide"],
    benefits: ["NVIDIA ESPP & Stock Grants", "Wellness allowances", "Comprehensive healthcare package", "Flexible work arrangements"],
    education: "MS or PhD in Computer Science / Computer Engineering",
    industry: "Hardware & AI Software",
    companySize: "10000+",
    applyUrl: "https://nvidia.com/careers/dl-compiler-engineer",
    sourceUrl: "https://nvidia.com/careers",
    source: "linkedin",
    isFeatured: true,
  },
  {
    title: "Staff Software Engineer - Infrastructure & Systems",
    company: "Stripe",
    location: "Remote / Bangalore, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Stripe Core Ingestion team is seeking a Staff Software Engineer to lead the architectural evolution of Stripe's high-reliability payment ledger system handling trillions of financial transactions.",
    salaryMin: 5000000,
    salaryMax: 8500000,
    experienceMin: 8,
    experienceMax: 15,
    employmentType: "Full-Time",
    workMode: "Remote",
    skills: ["Ruby", "Go", "Java", "Distributed Systems", "PostgreSQL", "Kafka", "AWS", "Architecture"],
    requirements: ["8+ years of experience designing mission-critical distributed storage and messaging systems", "Proven technical leadership across engineering organizations", "Mastery of database consistency models, ACID transactions, and fault isolation", "Strong passion for code craftsmanship and API design simplicity"],
    responsibilities: ["Architect next-generation multi-region active-active storage layer", "Define engineering standards and technical roadmaps across infrastructure", "Mentor senior engineers and staff candidates", "Represent technical decisions to executive leadership"],
    benefits: ["High equity package", "100% Remote flexibility", "Comprehensive health & dental insurance", "Generous parental leaves and sabbatical program"],
    education: "Bachelor's or Master's in CS",
    industry: "FinTech",
    companySize: "5001-10000",
    applyUrl: "https://stripe.com/careers/staff-engineer",
    sourceUrl: "https://stripe.com/careers",
    source: "wellfound",
    isFeatured: true,
  },
  {
    title: "Software Engineer Intern (Summer 2026)",
    company: "Meta",
    location: "Gurgaon, Haryana, India",
    country: "India",
    state: "Haryana",
    city: "Gurgaon",
    description: "Meta is accepting applications for Software Engineer Interns for Summer 2026. Work alongside Meta engineers on Instagram, WhatsApp, or Reality Labs platforms.",
    salaryMin: 800000,
    salaryMax: 1500000,
    experienceMin: 0,
    experienceMax: 1,
    employmentType: "Internship",
    workMode: "Onsite",
    skills: ["C++", "Python", "Java", "React", "Data Structures", "Algorithms", "Git"],
    requirements: ["Currently enrolled in a B.Tech / M.Tech / Dual Degree program in Computer Science or related field", "Graduating in 2026 or 2027", "Strong proficiency in Data Structures, Algorithms, and System Design basics", "Active competitive programming profile (Codeforces, LeetCode) is a plus"],
    responsibilities: ["Design and implement product features with mentorship from senior Meta engineers", "Write production-ready code with unit test coverage", "Participate in team code reviews and technical presentations", "Collaborate with cross-functional team members"],
    benefits: ["Competitive monthly stipend", "Relocation allowance & corporate housing", "Free daily meals and transportation", "Pre-Placement Offer (PPO) opportunity"],
    education: "Enrolled in B.Tech / M.Tech CS",
    industry: "Social Media & Tech",
    companySize: "10000+",
    applyUrl: "https://metacareers.com/jobs/software-engineer-intern",
    sourceUrl: "https://metacareers.com",
    source: "internshala",
    isFeatured: false,
  },
  {
    title: "Full Stack Developer (Node.js + React)",
    company: "Flipkart",
    location: "Bangalore, Karnataka, India",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    description: "Flipkart Customer Experience team is hiring Full Stack Engineers to build internal tools, seller dashboards, and high-conversion landing page engines.",
    salaryMin: 1800000,
    salaryMax: 3200000,
    experienceMin: 2,
    experienceMax: 5,
    employmentType: "Full-Time",
    workMode: "Hybrid",
    skills: ["Node.js", "React", "JavaScript", "TypeScript", "Express", "MongoDB", "Redis", "CSS"],
    requirements: ["2+ years experience building web applications with Node.js and React", "Strong understanding of RESTful API design, database modeling, and caching strategies", "Comfortable with Git workflows, Webpack, and Docker", "Good written and verbal communication skills"],
    responsibilities: ["Develop responsive frontend UI components and backend REST APIs", "Optimize application speed and database queries", "Collaborate with UI/UX designers and QA testers", "Participate in sprint planning and estimation"],
    benefits: ["Medical coverage for self & family", "Employee discounts on Flipkart", "Performance incentive bonus", "Flexible leave policy"],
    education: "B.Tech/BE in CS/IT",
    industry: "E-commerce",
    companySize: "10000+",
    applyUrl: "https://flipkartcareers.com/jobs/fullstack-developer",
    sourceUrl: "https://naukri.com",
    source: "naukri",
    isFeatured: false,
  },
];

async function main() {
  console.log("[SeedJobDiscovery] Connecting to database...");

  // 1. Seed Job Sources
  console.log("[SeedJobDiscovery] Seeding Job Sources...");
  for (const src of SOURCES) {
    await prisma.discoveryJobSource.upsert({
      where: { name: src.name },
      update: { displayName: src.displayName, isActive: true, schedule: src.schedule },
      create: {
        name: src.name,
        displayName: src.displayName,
        isActive: true,
        schedule: src.schedule,
      },
    });
  }
  console.log(`[SeedJobDiscovery] Seeded ${SOURCES.length} job sources.`);

  // 2. Seed Companies
  console.log("[SeedJobDiscovery] Seeding Companies...");
  for (const comp of COMPANIES) {
    const resolvedCompLogo = autoResolveCompanyLogo(comp.name, null);
    await prisma.discoveryCompany.upsert({
      where: { name: comp.name },
      update: {
        slug: comp.slug,
        logoUrl: resolvedCompLogo || null,
        industry: comp.industry,
        companySize: comp.companySize,
        website: comp.website,
        location: comp.location,
        techStack: comp.techStack,
        difficultyLevel: comp.difficultyLevel,
        description: comp.description,
      },
      create: {
        name: comp.name,
        slug: comp.slug,
        logoUrl: resolvedCompLogo || null,
        industry: comp.industry,
        companySize: comp.companySize,
        website: comp.website,
        location: comp.location,
        techStack: comp.techStack,
        difficultyLevel: comp.difficultyLevel,
        description: comp.description,
      },
    });
  }
  console.log(`[SeedJobDiscovery] Seeded ${COMPANIES.length} companies.`);

  // 3. Seed Jobs
  console.log("[SeedJobDiscovery] Seeding Jobs...");
  let count = 0;
  for (const job of JOBS_DATA) {
    const fingerprint = generateFingerprint(job.company, job.title, job.location, job.applyUrl);
    const resolvedJobLogo = autoResolveCompanyLogo(job.company, job.logoUrl);
    await prisma.discoveryJob.upsert({
      where: { fingerprint },
      update: {
        title: job.title,
        company: job.company,
        logoUrl: resolvedJobLogo || null,
        location: job.location,
        country: job.country,
        state: job.state,
        city: job.city,
        description: job.description,
        salaryMin: job.salaryMin,
        salaryMax: job.salaryMax,
        experienceMin: job.experienceMin,
        experienceMax: job.experienceMax,
        employmentType: job.employmentType,
        workMode: job.workMode,
        skills: job.skills,
        requirements: job.requirements,
        responsibilities: job.responsibilities,
        benefits: job.benefits,
        education: job.education,
        industry: job.industry,
        companySize: job.companySize,
        applyUrl: job.applyUrl,
        sourceUrl: job.sourceUrl,
        source: job.source,
        isFeatured: job.isFeatured,
        isActive: true,
        postedAt: new Date(Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000)),
      },
      create: {
        fingerprint,
        title: job.title,
        company: job.company,
        logoUrl: resolvedJobLogo || null,
        location: job.location,
        country: job.country,
        state: job.state,
        city: job.city,
        description: job.description,
        salaryMin: job.salaryMin,
        salaryMax: job.salaryMax,
        experienceMin: job.experienceMin,
        experienceMax: job.experienceMax,
        employmentType: job.employmentType,
        workMode: job.workMode,
        skills: job.skills,
        requirements: job.requirements,
        responsibilities: job.responsibilities,
        benefits: job.benefits,
        education: job.education,
        industry: job.industry,
        companySize: job.companySize,
        applyUrl: job.applyUrl,
        sourceUrl: job.sourceUrl,
        source: job.source,
        isFeatured: job.isFeatured,
        isActive: true,
        postedAt: new Date(Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000)),
      },
    });
    count++;
  }

  // Update company job counts
  for (const comp of COMPANIES) {
    const jobCount = await prisma.discoveryJob.count({
      where: { company: comp.name, isActive: true },
    });
    await prisma.discoveryCompany.update({
      where: { name: comp.name },
      data: { jobCount },
    }).catch(() => {});
  }

  console.log(`[SeedJobDiscovery] Successfully seeded ${count} high-quality discovery jobs!`);
}

main()
  .catch((e) => {
    console.error("[SeedJobDiscovery] Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
