import puppeteer from "puppeteer";
import { formatAssignmentHtml, AssignmentExportOptions } from "./assignment-formatter.service";

function escapeXml(text: string): string {
  return (text || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function generateAssignmentPdf(
  content: string,
  topicName: string,
  options: AssignmentExportOptions = {}
): Promise<Buffer> {
  const htmlContent = formatAssignmentHtml(content, topicName, options);
  const title = options.assignmentTitle || options.topic || topicName || "Academic Assignment";
  const dateStr = options.generatedOn || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 12px 40px 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-bottom: 1px solid #e2e8f0;
      margin: 0 40px;
      box-sizing: border-box;
    ">
      <span style="font-size: 10px; font-weight: 700; color: #0f172a; max-width: 350px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
        ${escapeXml(title)}
      </span>
      <span style="font-size: 9px; font-weight: 800; color: #f59e0b; text-transform: uppercase; letter-spacing: 0.5px;">
        ADYAPAN AI ASSIGNMENT GENERATOR
      </span>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 8px 40px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-top: 1px solid #e2e8f0;
      margin: 0 40px;
      box-sizing: border-box;
      font-size: 9px;
      color: #94a3b8;
    ">
      <span>Generated by Adyapan AI &middot; www.adyapanai.com</span>
      <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      <span>Confidential &middot; Academic Copy</span>
    </div>
  `;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
      ],
    });

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0", timeout: 60000 });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "70px",
        bottom: "60px",
        left: "40px",
        right: "40px",
      },
    });

    return Buffer.from(pdfBuffer);
  } catch (error) {
    console.error("[Assignment PDF] Puppeteer error:", error);
    throw error;
  } finally {
    if (browser) {
      await browser.close().catch(() => {});
    }
  }
}
