import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  BorderStyle,
  WidthType,
  AlignmentType,
  ShadingType,
  HeadingLevel,
  PageBreak,
} from "docx";
import { AssignmentExportOptions } from "./assignment-formatter.service";

function createMetaCell(label: string, value: string): TableCell {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    shading: { fill: "F8FAFC", type: ShadingType.CLEAR },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
      left: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
      right: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
    },
    children: [
      new Paragraph({
        children: [
          new TextRun({ text: `${label.toUpperCase()}: `, bold: true, size: 18, color: "94A3B8" }),
          new TextRun({ text: value, bold: true, size: 20, color: "0F172A" }),
        ],
      }),
    ],
  });
}

export async function generateAssignmentDocx(
  markdown: string,
  topicName: string,
  options: AssignmentExportOptions = {}
): Promise<Buffer> {
  const title = options.assignmentTitle || options.topic || topicName || "Academic Assignment";
  const subject = options.subject || "Academic Study";
  const course = options.course || "B.Tech / Degree Course";
  const semester = options.semester || "Semester 6";
  const studentName = options.studentName || "Ashish Kumar";
  const regNumber = options.registrationNumber || "REG-2026-12219027";
  const faculty = options.faculty || "Faculty Department";
  const university = options.university || "Lovely Professional University";
  const academicLevel = options.academicLevel || "Undergraduate";
  const wordCount = options.wordCount || (markdown ? markdown.split(/\s+/).length : 2500);
  const dateStr = options.generatedOn || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const assignmentId = options.assignmentId || `ASSIGN-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.floor(1000 + Math.random() * 9000)}`;

  const children: (Paragraph | Table)[] = [];

  // ================= COVER PAGE =================
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 100 },
      children: [
        new TextRun({ text: "🎓 ADYAPAN AI", bold: true, size: 38, color: "F4B400" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      children: [
        new TextRun({ text: "AI ASSIGNMENT GENERATOR ENGINE", bold: true, size: 20, color: "64748B" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 300, after: 100 },
      children: [
        new TextRun({ text: title, bold: true, size: 44, color: "111827" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({ text: "Publication-Grade Academic Research Assignment", italics: true, size: 24, color: "6B7280" }),
      ],
    })
  );

  // Cover Page Student Metadata Table
  const coverMetaTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          createMetaCell("Submitted By", studentName),
          createMetaCell("Registration No.", regNumber),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Subject & Course", `${subject} (${course})`),
          createMetaCell("Semester", semester),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Faculty Supervisor", faculty),
          createMetaCell("Institution", university),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Academic Level", academicLevel),
          createMetaCell("Submission Date", dateStr),
        ],
      }),
    ],
  });

  children.push(coverMetaTable);

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 200 },
      children: [
        new TextRun({ text: `Generated by Adyapan AI · ${assignmentId}`, size: 18, color: "94A3B8" }),
      ],
    }),
    new Paragraph({
      children: [new PageBreak()],
    })
  );

  // ================= ASSIGNMENT METADATA BOX =================
  const infoTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          createMetaCell("Assignment Title", title),
          createMetaCell("Subject", subject),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Academic Level", academicLevel),
          createMetaCell("Word Count", `${wordCount} words`),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Assignment ID", assignmentId),
          createMetaCell("Generated On", dateStr),
        ],
      }),
    ],
  });

  children.push(infoTable);

  children.push(
    new Paragraph({
      spacing: { after: 200 },
      children: [],
    })
  );

  // ================= PARSE MARKDOWN BODY =================
  const lines = (markdown || "").split("\n");
  let inCodeBlock = false;
  let codeBuffer: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith("```")) {
      if (inCodeBlock) {
        // End code block
        children.push(
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    shading: { fill: "0F172A", type: ShadingType.CLEAR },
                    borders: {
                      top: { style: BorderStyle.SINGLE, size: 1, color: "1E293B" },
                      bottom: { style: BorderStyle.SINGLE, size: 1, color: "1E293B" },
                      left: { style: BorderStyle.SINGLE, size: 1, color: "1E293B" },
                      right: { style: BorderStyle.SINGLE, size: 1, color: "1E293B" },
                    },
                    children: codeBuffer.map(
                      codeLine =>
                        new Paragraph({
                          children: [
                            new TextRun({ text: codeLine, size: 19, color: "F8FAFC", font: "Courier New" }),
                          ],
                        })
                    ),
                  }),
                ],
              }),
            ],
          })
        );
        codeBuffer = [];
        inCodeBlock = false;
      } else {
        inCodeBlock = true;
      }
      continue;
    }

    if (inCodeBlock) {
      codeBuffer.push(line);
      continue;
    }

    if (!trimmed) {
      children.push(new Paragraph({ spacing: { after: 100 } }));
      continue;
    }

    if (trimmed.startsWith("# ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 120 },
          children: [
            new TextRun({ text: trimmed.replace(/^#\s+/, ""), bold: true, size: 28, color: "0F172A" }),
          ],
        })
      );
    } else if (trimmed.startsWith("## ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 100 },
          children: [
            new TextRun({ text: trimmed.replace(/^##\s+/, ""), bold: true, size: 24, color: "1E293B" }),
          ],
        })
      );
    } else if (trimmed.startsWith("### ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 180, after: 80 },
          children: [
            new TextRun({ text: trimmed.replace(/^###\s+/, ""), bold: true, size: 20, color: "334155" }),
          ],
        })
      );
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 80 },
          children: [
            new TextRun({ text: trimmed.replace(/^[-*]\s+/, ""), size: 22, color: "1E293B" }),
          ],
        })
      );
    } else if (/^\d+\.\s/.test(trimmed)) {
      children.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [
            new TextRun({ text: trimmed, size: 22, color: "1E293B" }),
          ],
        })
      );
    } else if (trimmed.startsWith(">")) {
      children.push(
        new Paragraph({
          spacing: { before: 100, after: 100 },
          children: [
            new TextRun({ text: "💡 " + trimmed.replace(/^>\s*/, ""), italics: true, size: 21, color: "D97706" }),
          ],
        })
      );
    } else {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: [
            new TextRun({ text: line, size: 22, color: "111827" }),
          ],
        })
      );
    }
  }

  // Create Document with Headers & Footers
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 inch
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: `${title} | ADYAPAN AI ASSIGNMENT GENERATOR`,
                    bold: true,
                    size: 16,
                    color: "F4B400",
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Generated by Adyapan AI · www.adyapanai.com · Page ",
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    text: " of ",
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    size: 16,
                    color: "94A3B8",
                  }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
