import puppeteer from "puppeteer";
import PDFDocument from "pdfkit";
import { formatAssignmentHtml, AssignmentExportOptions } from "./assignment-formatter.service";

function escapeXml(text: string): string {
  return (text || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function generateAssignmentPdfKitFallback(content: string, topicName: string, options: AssignmentExportOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 48 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const title = options.assignmentTitle || options.topic || topicName || "Academic Assignment";

      // Top Banner
      doc.rect(0, 0, 595, 50).fill("#0F172A");
      doc.fillColor("#F59E0B").fontSize(16).font("Helvetica-Bold").text("Adyapan AI", 48, 16);
      doc.fillColor("#94A3B8").fontSize(9).font("Helvetica").text("Academic Assignment Generator", 180, 20);
      
      doc.y = 70;

      // Title
      doc.fillColor("#0F172A").fontSize(18).font("Helvetica-Bold").text(title);
      doc.moveDown(0.3);
      doc.strokeColor("#E2E8F0").lineWidth(1).moveTo(48, doc.y).lineTo(547, doc.y).stroke();
      doc.moveDown(0.6);

      // Markdown Content Parsing
      const textContent = typeof content === "string" ? content : String(content || "");
      const lines = textContent.split("\n");

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.2);
          continue;
        }

        if (trimmed.startsWith("# ")) {
          doc.moveDown(0.3);
          doc.fillColor("#0F172A").fontSize(15).font("Helvetica-Bold").text(trimmed.replace(/^#\s+/, ""));
          doc.moveDown(0.2);
        } else if (trimmed.startsWith("## ")) {
          doc.moveDown(0.2);
          doc.fillColor("#D97706").fontSize(13).font("Helvetica-Bold").text(trimmed.replace(/^##\s+/, ""));
          doc.moveDown(0.2);
        } else if (trimmed.startsWith("### ")) {
          doc.moveDown(0.2);
          doc.fillColor("#334155").fontSize(11).font("Helvetica-Bold").text(trimmed.replace(/^###\s+/, ""));
          doc.moveDown(0.15);
        } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
          const itemText = trimmed.replace(/^[-*]\s+/, "").replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#1E293B").fontSize(9.5).font("Helvetica").text(`• ${itemText}`, { indent: 12 });
          doc.moveDown(0.1);
        } else if (trimmed.startsWith("> ")) {
          const calloutText = trimmed.replace(/^>\s*/, "").replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#B45309").fontSize(9.5).font("Helvetica-Oblique").text(`Note: ${calloutText}`, { indent: 14 });
          doc.moveDown(0.15);
        } else {
          const plainText = trimmed.replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#1E293B").fontSize(9.5).font("Helvetica").text(plainText);
          doc.moveDown(0.15);
        }
      }

      // Footer
      doc.moveDown(1);
      doc.fillColor("#94A3B8").fontSize(8).font("Helvetica").text(`Generated by Adyapan AI Engine · ${new Date().toLocaleDateString()}`, { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function generateAssignmentPdf(
  content: string,
  topicName: string,
  options: AssignmentExportOptions = {}
): Promise<Buffer> {
  const htmlContent = formatAssignmentHtml(content, topicName, options);
  const title = options.assignmentTitle || options.topic || topicName || "Academic Assignment";
  const dateStr = options.generatedOn || new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 12px 40px 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-bottom: 1px solid #e2e8f0;
      margin: 0 40px;
      box-sizing: border-box;
    ">
      <span style="font-size: 10px; font-weight: 700; color: #0f172a; max-width: 350px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
        ${escapeXml(title)}
      </span>
      <span style="font-size: 9px; font-weight: 800; color: #f59e0b; text-transform: uppercase; letter-spacing: 0.5px;">
        ADYAPAN AI ASSIGNMENT GENERATOR
      </span>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 8px 40px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      border-top: 1px solid #e2e8f0;
      margin: 0 40px;
      box-sizing: border-box;
      font-size: 9px;
      color: #94a3b8;
    ">
      <span>Generated by Adyapan AI &middot; www.adyapanai.com</span>
      <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      <span>Confidential &middot; Academic Copy</span>
    </div>
  `;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
      ],
    });

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "domcontentloaded", timeout: 20000 });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "70px",
        bottom: "60px",
        left: "40px",
        right: "40px",
      },
    });

    return Buffer.from(pdfBuffer);
  } catch (error) {
    console.warn("[Assignment PDF] Puppeteer failed, using PDFKit fallback:", error);
    return generateAssignmentPdfKitFallback(content, topicName, options);
  } finally {
    if (browser) {
      await browser.close().catch(() => {});
    }
  }
}
