import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  BorderStyle,
  WidthType,
  AlignmentType,
  ShadingType,
  HeadingLevel,
} from "docx";

interface ExportOptions {
  subject?: string;
  topic?: string;
  difficulty?: string;
  language?: string;
  generatedBy?: string;
  readingTime?: string;
  wordCount?: number;
  exportId?: string;
  type?: string;
}

export async function generateNotesDocx(
  markdown: string,
  topicName: string,
  options: ExportOptions = {}
): Promise<Buffer> {
  const subject = options.subject || "Study Notes";
  const topic = options.topic || topicName;
  const difficulty = options.difficulty || "Intermediate";
  const language = options.language || "English";
  const generatedBy = options.generatedBy || "Adyapan AI Engine";
  const readingTime = options.readingTime || `${Math.ceil((options.wordCount || 1000) / 200)} min`;
  const wordCount = options.wordCount || markdown.split(/\s+/).length;
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const exportId = options.exportId || `ADY-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.floor(1000 + Math.random() * 9000)}`;

  const children: (Paragraph | Table)[] = [];

  // Header Brand Block
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "ADYAPAN AI", bold: true, size: 36, color: "F4B400" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 },
      children: [
        new TextRun({ text: "AI Notes Generator", bold: true, size: 24, color: "111827" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: '"Powered by Artificial Intelligence"', italics: true, size: 18, color: "6B7280" }),
      ],
    })
  );

  // Metadata Table
  const metaTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          createMetaCell("Subject", subject),
          createMetaCell("Topic", topic),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Difficulty", difficulty),
          createMetaCell("Language", language),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Generated On", dateStr),
          createMetaCell("Generated By", generatedBy),
        ],
      }),
      new TableRow({
        children: [
          createMetaCell("Word Count", `${wordCount}`),
          createMetaCell("Export ID", exportId),
        ],
      }),
    ],
  });

  children.push(metaTable);
  children.push(new Paragraph({ spacing: { after: 300 } }));

  // Main Topic Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 240, after: 120 },
      children: [
        new TextRun({ text: topic, bold: true, color: "F4B400", size: 32 }),
      ],
    })
  );

  // Parse markdown content into DOCX elements
  const lines = markdown.split("\n");
  let inCodeBlock = false;
  let codeBuffer: string[] = [];

  for (const line of lines) {
    if (line.trim().startsWith("```")) {
      if (inCodeBlock) {
        // End code block
        children.push(createCodeBlockTable(codeBuffer.join("\n")));
        codeBuffer = [];
        inCodeBlock = false;
      } else {
        inCodeBlock = true;
      }
      continue;
    }

    if (inCodeBlock) {
      codeBuffer.push(line);
      continue;
    }

    const trimmed = line.trim();
    if (!trimmed) {
      children.push(new Paragraph({ spacing: { after: 120 } }));
      continue;
    }

    if (trimmed.startsWith("# ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 280, after: 120 },
          children: [new TextRun({ text: trimmed.replace(/^#\s+/, ""), bold: true, color: "111827", size: 28 })],
        })
      );
    } else if (trimmed.startsWith("## ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 100 },
          children: [new TextRun({ text: trimmed.replace(/^##\s+/, ""), bold: true, color: "D97706", size: 24 })],
        })
      );
    } else if (trimmed.startsWith("### ")) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
          children: [new TextRun({ text: trimmed.replace(/^###\s+/, ""), bold: true, color: "374151", size: 20 })],
        })
      );
    } else if (trimmed.startsWith("> ")) {
      // Callout box
      children.push(createCalloutTable(trimmed.replace(/^>\s*/, "")));
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      const itemText = trimmed.replace(/^[-*]\s+/, "");
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 60 },
          children: [new TextRun({ text: parseInlineBold(itemText), size: 22 })],
        })
      );
    } else {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: parseInlineRuns(trimmed),
        })
      );
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 720, bottom: 720, left: 720, right: 720 },
          },
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Generated by Adyapan AI  |  www.adyapanai.com  |  Page ", size: 18, color: "9CA3AF" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18, color: "9CA3AF" }),
                  new TextRun({ text: " of ", size: 18, color: "9CA3AF" }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: "9CA3AF" }),
                  new TextRun({ text: "  |  Confidential", size: 18, color: "9CA3AF" }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

function createMetaCell(label: string, value: string): TableCell {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    shading: { fill: "F9FAFB", type: ShadingType.CLEAR },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
      left: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
      right: { style: BorderStyle.SINGLE, size: 1, color: "E5E7EB" },
    },
    children: [
      new Paragraph({
        children: [
          new TextRun({ text: `${label}: `, bold: true, size: 20, color: "4B5563" }),
          new TextRun({ text: value, size: 20, color: "111827" }),
        ],
      }),
    ],
  });
}

function createCodeBlockTable(code: string): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            shading: { fill: "1E1E2E", type: ShadingType.CLEAR },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 1, color: "313244" },
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "313244" },
              left: { style: BorderStyle.SINGLE, size: 1, color: "313244" },
              right: { style: BorderStyle.SINGLE, size: 1, color: "313244" },
            },
            children: code.split("\n").map(
              (line) =>
                new Paragraph({
                  children: [new TextRun({ text: line || " ", font: "Consolas", size: 20, color: "F59E0B" })],
                })
            ),
          }),
        ],
      }),
    ],
  });
}

function createCalloutTable(text: string): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            shading: { fill: "FEF3C7", type: ShadingType.CLEAR },
            borders: {
              left: { style: BorderStyle.SINGLE, size: 12, color: "F59E0B" },
              top: { style: BorderStyle.NONE, size: 0, color: "AUTO" },
              right: { style: BorderStyle.NONE, size: 0, color: "AUTO" },
              bottom: { style: BorderStyle.NONE, size: 0, color: "AUTO" },
            },
            children: [
              new Paragraph({
                children: [new TextRun({ text, italics: true, size: 22, color: "92400E" })],
              }),
            ],
          }),
        ],
      }),
    ],
  });
}

function parseInlineBold(text: string): string {
  return text.replace(/\*\*(.*?)\*\*/g, "$1");
}

function parseInlineRuns(text: string): TextRun[] {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return new TextRun({ text: part.slice(2, -2), bold: true, size: 22, color: "111827" });
    }
    return new TextRun({ text: part, size: 22, color: "374151" });
  });
}
