import puppeteer from "puppeteer";
import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { formatNotesHtml, NotesFormatOptions } from "./notes-formatter.service";

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

let cachedLogoBase64: string | null = null;
function getLogoBase64(): string {
  if (cachedLogoBase64) return cachedLogoBase64;
  try {
    const cwd = process.cwd();
    const candidatePaths = [
      path.resolve(cwd, "frontend/public/assets/logo.png"),
      path.resolve(cwd, "../frontend/public/assets/logo.png"),
      path.resolve(cwd, "public/assets/logo.png"),
      path.resolve(__dirname, "../../../frontend/public/assets/logo.png"),
      path.resolve(__dirname, "../../frontend/public/assets/logo.png"),
      path.resolve(__dirname, "../../public/assets/logo.png"),
    ];
    for (const p of candidatePaths) {
      if (fs.existsSync(p)) {
        const fileBuf = fs.readFileSync(p);
        cachedLogoBase64 = `data:image/png;base64,${fileBuf.toString("base64")}`;
        return cachedLogoBase64;
      }
    }
  } catch (err) {
    console.warn("[PDF Generator] Could not load logo image for PDF header:", err);
  }
  return "";
}

function buildHeaderFooterTemplates(topic: string) {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const logoDataUri = getLogoBase64();
  const logoHtml = logoDataUri
    ? `<img src="${logoDataUri}" style="width: 22px; height: 22px; border-radius: 50%; object-fit: contain; vertical-align: middle; display: inline-block;" />`
    : `<span style="display: inline-block; width: 22px; height: 22px; border-radius: 50%; background: linear-gradient(135deg, #F59E0B, #D97706); color: #000; font-weight: 900; font-size: 11px; text-align: center; line-height: 22px; vertical-align: middle;">A</span>`;

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 0 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      box-sizing: border-box;
    ">
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #e2e8f0;
        padding-bottom: 6px;
        font-size: 10px;
        color: #64748b;
      ">
        <div style="display: flex; align-items: center; gap: 8px;">
          ${logoHtml}
          <span style="font-weight: 800; color: #0f172a; letter-spacing: -0.01em; font-size: 11px;">Adyapan AI</span>
          <span style="color: #cbd5e1;">&middot;</span>
          <span style="font-weight: 600; color: #475569; max-width: 380px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${escapeXml(topic)}</span>
        </div>
        <div style="font-size: 9px; color: #94a3b8; font-weight: 500;">${dateStr}</div>
      </div>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 0 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      box-sizing: border-box;
    ">
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-top: 1px solid #e2e8f0;
        padding-top: 6px;
        font-size: 9.5px;
        color: #94a3b8;
      ">
        <div style="display: flex; align-items: center; gap: 6px;">
          ${logoHtml}
          <span>Generated by <strong>Adyapan AI</strong> &middot; www.adyapan.com</span>
        </div>
        <div>Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
        <div>&copy; ${new Date().getFullYear()} Adyapan AI</div>
      </div>
    </div>
  `;

  return { headerTemplate, footerTemplate };
}

/** Fallback PDF generator using pure PDFKit if Puppeteer fails */
function generateNotesPdfKitFallback(markdown: string, topic: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 48 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Top Banner
      doc.rect(0, 0, 595, 50).fill("#0F172A");
      doc.fillColor("#F59E0B").fontSize(16).font("Helvetica-Bold").text("Adyapan AI", 48, 16);
      doc.fillColor("#94A3B8").fontSize(9).font("Helvetica").text(`Study Notes · ${topic}`, 180, 20);
      
      doc.y = 70;

      // Title
      doc.fillColor("#0F172A").fontSize(18).font("Helvetica-Bold").text(topic);
      doc.moveDown(0.3);
      doc.strokeColor("#E2E8F0").lineWidth(1).moveTo(48, doc.y).lineTo(547, doc.y).stroke();
      doc.moveDown(0.6);

      // Markdown Content Parsing
      const textContent = typeof markdown === "string" ? markdown : String(markdown || "");
      const lines = textContent.split("\n");

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.2);
          continue;
        }

        if (trimmed.startsWith("# ")) {
          doc.moveDown(0.3);
          doc.fillColor("#0F172A").fontSize(15).font("Helvetica-Bold").text(trimmed.replace(/^#\s+/, ""));
          doc.moveDown(0.2);
        } else if (trimmed.startsWith("## ")) {
          doc.moveDown(0.2);
          doc.fillColor("#D97706").fontSize(13).font("Helvetica-Bold").text(trimmed.replace(/^##\s+/, ""));
          doc.moveDown(0.2);
        } else if (trimmed.startsWith("### ")) {
          doc.moveDown(0.2);
          doc.fillColor("#334155").fontSize(11).font("Helvetica-Bold").text(trimmed.replace(/^###\s+/, ""));
          doc.moveDown(0.15);
        } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
          const itemText = trimmed.replace(/^[-*]\s+/, "").replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#1E293B").fontSize(9.5).font("Helvetica").text(`• ${itemText}`, { indent: 12 });
          doc.moveDown(0.1);
        } else if (trimmed.startsWith("> ")) {
          const calloutText = trimmed.replace(/^>\s*/, "").replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#B45309").fontSize(9.5).font("Helvetica-Oblique").text(`Note: ${calloutText}`, { indent: 14 });
          doc.moveDown(0.15);
        } else {
          const plainText = trimmed.replace(/\*\*(.*?)\*\*/g, "$1");
          doc.fillColor("#1E293B").fontSize(9.5).font("Helvetica").text(plainText);
          doc.moveDown(0.15);
        }
      }

      // Footer
      doc.moveDown(1);
      doc.fillColor("#94A3B8").fontSize(8).font("Helvetica").text(`Generated by Adyapan AI Engine · ${new Date().toLocaleDateString()}`, { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate a professional PDF from raw markdown notes.
 * Includes Adyapan AI header/footer, page numbers, and professional layout.
 */
export async function generateNotesPdf(
  markdown: string,
  topic: string,
  options?: NotesFormatOptions
): Promise<Buffer> {
  const htmlContent = formatNotesHtml(markdown, topic, options);
  const { headerTemplate, footerTemplate } = buildHeaderFooterTemplates(topic);

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    const cspMeta = '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src https: data: blob:; style-src \'unsafe-inline\' https://fonts.googleapis.com; font-src https://fonts.gstatic.com data:;">';
    const hardenedHtml = htmlContent.replace("<head>", `<head>${cspMeta}`);

    await page.setContent(hardenedHtml, {
      waitUntil: "domcontentloaded",
      timeout: 20000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "18mm",
        bottom: "16mm",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 30000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.warn(
      "[PDF Generator] Puppeteer failed, using PDFKit fallback:",
      error?.message || error
    );
    return generateNotesPdfKitFallback(markdown, topic);
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}

/**
 * Generate a PDF from pre-formatted HTML content.
 * Useful when the HTML has already been formatted by formatNotesHtml.
 */
export async function generatePdfFromHtml(
  htmlContent: string,
  topic: string
): Promise<Buffer> {
  const { headerTemplate, footerTemplate } = buildHeaderFooterTemplates(topic);

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    const cspMeta = '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src https: data: blob:; style-src \'unsafe-inline\' https://fonts.googleapis.com; font-src https://fonts.gstatic.com data:;">';
    const hardenedHtml = htmlContent.replace("<head>", `<head>${cspMeta}`);

    await page.setContent(hardenedHtml, {
      waitUntil: "domcontentloaded",
      timeout: 20000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "18mm",
        bottom: "16mm",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 30000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.warn(
      "[PDF Generator] Puppeteer failed in HTML mode, using PDFKit fallback:",
      error?.message || error
    );
    const plainMarkdown = htmlContent.replace(/<[^>]+>/g, "\n");
    return generateNotesPdfKitFallback(plainMarkdown, topic);
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}
