import puppeteer from "puppeteer";
import fs from "fs";
import path from "path";
import { formatNotesHtml, NotesFormatOptions } from "./notes-formatter.service";

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

let cachedLogoBase64: string | null = null;
function getLogoBase64(): string {
  if (cachedLogoBase64 !== null) return cachedLogoBase64;
  try {
    const cwd = process.cwd();
    const candidatePaths = [
      path.join(cwd, "frontend", "public", "assets", "logo.png"),
      path.join(cwd, "..", "frontend", "public", "assets", "logo.png"),
      path.join(__dirname, "..", "..", "..", "frontend", "public", "assets", "logo.png"),
      path.join(__dirname, "..", "..", "public", "assets", "logo.png"),
    ];
    for (const p of candidatePaths) {
      if (fs.existsSync(p)) {
        const fileBuf = fs.readFileSync(p);
        cachedLogoBase64 = `data:image/png;base64,${fileBuf.toString("base64")}`;
        return cachedLogoBase64;
      }
    }
  } catch { /* fallback */ }
  cachedLogoBase64 = "";
  return cachedLogoBase64;
}

function buildHeaderFooterTemplates(topic: string) {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const logoDataUri = getLogoBase64();
  const logoHtml = logoDataUri
    ? `<img src="${logoDataUri}" style="width: 14px; height: 14px; border-radius: 50%; object-fit: contain; vertical-align: middle;" />`
    : `<span style="display: inline-block; width: 14px; height: 14px; border-radius: 4px; background: linear-gradient(135deg, #F59E0B, #D97706); color: #000; font-weight: 900; font-size: 9px; text-align: center; line-height: 14px; vertical-align: middle;">A</span>`;

  const headerTemplate = `
    <div style="
      width: 100%;
      padding: 0 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      box-sizing: border-box;
    ">
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #e2e8f0;
        padding-bottom: 4px;
        font-size: 9.5px;
        color: #64748b;
      ">
        <div style="display: flex; align-items: center; gap: 6px;">
          ${logoHtml}
          <span style="font-weight: 800; color: #0f172a; letter-spacing: -0.01em;">Adyapan AI</span>
          <span style="color: #cbd5e1;">&middot;</span>
          <span style="font-weight: 600; color: #475569; max-width: 380px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${escapeXml(topic)}</span>
        </div>
        <div style="font-size: 8.5px; color: #94a3b8; font-weight: 500;">${dateStr}</div>
      </div>
    </div>
  `;

  const footerTemplate = `
    <div style="
      width: 100%;
      padding: 0 48px;
      font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
      box-sizing: border-box;
    ">
      <div style="
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-top: 1px solid #e2e8f0;
        padding-top: 4px;
        font-size: 9px;
        color: #94a3b8;
      ">
        <div style="display: flex; align-items: center; gap: 4px;">
          ${logoHtml}
          <span>Generated by <strong>Adyapan AI</strong> &middot; www.adyapanai.com</span>
        </div>
        <div>Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
        <div>&copy; ${new Date().getFullYear()} Adyapan AI</div>
      </div>
    </div>
  `;

  return { headerTemplate, footerTemplate };
}

/**
 * Generate a professional PDF from raw markdown notes.
 * Includes Adyapan AI header/footer, page numbers, and professional layout.
 */
export async function generateNotesPdf(
  markdown: string,
  topic: string,
  options?: NotesFormatOptions
): Promise<Buffer> {
  const htmlContent = formatNotesHtml(markdown, topic, options);
  const { headerTemplate, footerTemplate } = buildHeaderFooterTemplates(topic);

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, {
      waitUntil: "domcontentloaded",
      timeout: 30000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "18mm",
        bottom: "16mm",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 60000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.error(
      "[PDF Generator] Error generating PDF:",
      error?.message || error
    );
    throw new Error(
      `PDF generation failed: ${error?.message || "Unknown error"}`
    );
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}

/**
 * Generate a PDF from pre-formatted HTML content.
 * Useful when the HTML has already been formatted by formatNotesHtml.
 */
export async function generatePdfFromHtml(
  htmlContent: string,
  topic: string
): Promise<Buffer> {
  const { headerTemplate, footerTemplate } = buildHeaderFooterTemplates(topic);

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, {
      waitUntil: "domcontentloaded",
      timeout: 30000,
    });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: {
        top: "18mm",
        bottom: "16mm",
        left: "0px",
        right: "0px",
      },
      preferCSSPageSize: false,
      timeout: 60000,
    });

    return Buffer.from(pdfBuffer);
  } catch (error: any) {
    console.error(
      "[PDF Generator] Error generating PDF from HTML:",
      error?.message || error
    );
    throw new Error(
      `PDF generation failed: ${error?.message || "Unknown error"}`
    );
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch {
        // Ignore close errors
      }
    }
  }
}
