export interface InterviewDomain {
  id: string;
  name: string;
  role: string;
  category:
    | "CSE & IT Domains"
    | "Design & Creative"
    | "Management & Business"
    | "Core Engineering"
    | "ECE & Robotics"
    | "Healthcare & Pharma";
  tech: string;
  description: string;
  defaultLang?: "python" | "javascript" | "java" | "cpp" | "sql";
  iconName: string;
  isCseCore?: boolean;
}

export const INTERVIEW_DOMAIN_CATEGORIES = [
  "All",
  "CSE & IT Domains",
  "Design & Creative",
  "Management & Business",
  "Core Engineering",
  "ECE & Robotics",
  "Healthcare & Pharma",
] as const;

export type InterviewDomainCategory = typeof INTERVIEW_DOMAIN_CATEGORIES[number];

export const ALL_INTERVIEW_DOMAINS: InterviewDomain[] = [
  // ── 18 Core Adyapan CSE Domains (From Flyer) ──
  {
    id: "data-science",
    name: "Data Science",
    role: "Data Scientist",
    category: "CSE & IT Domains",
    tech: "Python, Pandas, NumPy, Scikit-learn, EDA",
    description: "EDA, statistics, pandas, predictive modeling & feature engineering",
    defaultLang: "python",
    iconName: "Database",
    isCseCore: true,
  },
  {
    id: "ml-python",
    name: "ML with Python",
    role: "Machine Learning Engineer",
    category: "CSE & IT Domains",
    tech: "Python, Scikit-learn, TensorFlow, PyTorch",
    description: "Scikit-learn, classification, regression, clustering & ML pipelines",
    defaultLang: "python",
    iconName: "Brain",
    isCseCore: true,
  },
  {
    id: "ai-ml",
    name: "AI with ML",
    role: "AI / ML Engineer",
    category: "CSE & IT Domains",
    tech: "Deep Learning, Neural Networks, Computer Vision, NLP, PyTorch",
    description: "Deep learning, neural networks, PyTorch, computer vision & NLP",
    defaultLang: "python",
    iconName: "Brain",
    isCseCore: true,
  },
  {
    id: "python-programming",
    name: "Programming in Python",
    role: "Python Developer",
    category: "CSE & IT Domains",
    tech: "Python, OOP, AsyncIO, FastAPI, Generators",
    description: "Core Python, OOP, memory model, decorators, generators & async",
    defaultLang: "python",
    iconName: "Terminal",
    isCseCore: true,
  },
  {
    id: "fullstack",
    name: "Full Stack Web Development",
    role: "Full Stack Developer",
    category: "CSE & IT Domains",
    tech: "React, Next.js, Node.js, Express, PostgreSQL",
    description: "End-to-end web apps, React, Node.js, REST/GraphQL APIs & databases",
    defaultLang: "javascript",
    iconName: "Layers",
    isCseCore: true,
  },
  {
    id: "web-dev",
    name: "Web Development",
    role: "Web Developer",
    category: "CSE & IT Domains",
    tech: "HTML5, CSS3, JavaScript, Tailwind, DOM",
    description: "HTML5, CSS3, JavaScript ES6+, DOM manipulation & responsive UI",
    defaultLang: "javascript",
    iconName: "Globe",
    isCseCore: true,
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    role: "Cybersecurity Analyst",
    category: "CSE & IT Domains",
    tech: "Network Security, OWASP, Penetration Testing, Cryptography",
    description: "OWASP Top 10, penetration testing, cryptography & network defenses",
    defaultLang: "python",
    iconName: "Shield",
    isCseCore: true,
  },
  {
    id: "cloud-computing",
    name: "Cloud Computing",
    role: "Cloud Engineer",
    category: "CSE & IT Domains",
    tech: "Cloud Architecture, Docker, Kubernetes, Virtualization",
    description: "Cloud architecture, IaaS/PaaS, virtualization, scalability & security",
    defaultLang: "python",
    iconName: "Cloud",
    isCseCore: true,
  },
  {
    id: "java-programming",
    name: "Programming in Java",
    role: "Java Developer",
    category: "CSE & IT Domains",
    tech: "Core Java, JVM, Multithreading, Spring Boot",
    description: "Core Java, JVM internals, multithreading, collections & OOP patterns",
    defaultLang: "java",
    iconName: "Code2",
    isCseCore: true,
  },
  {
    id: "ai",
    name: "AI (Artificial Intelligence)",
    role: "AI Specialist",
    category: "CSE & IT Domains",
    tech: "Search Algorithms, Expert Systems, Reinforcement Learning",
    description: "Search algorithms, heuristic search, knowledge bases & expert systems",
    defaultLang: "python",
    iconName: "Sparkles",
    isCseCore: true,
  },
  {
    id: "android-dev",
    name: "Android App Development",
    role: "Android Developer",
    category: "CSE & IT Domains",
    tech: "Kotlin, Android SDK, Jetpack Compose, MVVM, Room",
    description: "Kotlin, Android SDK, Jetpack Compose, MVVM & Room database",
    defaultLang: "java",
    iconName: "Smartphone",
    isCseCore: true,
  },
  {
    id: "data-analytics",
    name: "Data Analytics",
    role: "Data Analyst",
    category: "CSE & IT Domains",
    tech: "SQL, Power BI, Tableau, Excel, Data Warehousing",
    description: "SQL queries, ETL pipelines, KPI dashboards & business insights",
    defaultLang: "python",
    iconName: "BarChart3",
    isCseCore: true,
  },
  {
    id: "business-analytics",
    name: "Business Analytics",
    role: "Business Analyst",
    category: "CSE & IT Domains",
    tech: "KPI Metrics, Unit Economics, Forecasting, A/B Testing",
    description: "Quantitative problem solving, unit economics, cohorts & A/B testing",
    defaultLang: "python",
    iconName: "TrendingUp",
    isCseCore: true,
  },
  {
    id: "dsa-python",
    name: "DSA with Python",
    role: "Software Development Engineer",
    category: "CSE & IT Domains",
    tech: "Data Structures & Algorithms, LeetCode, Python",
    description: "LeetCode patterns, trees, graphs, dynamic programming & complexity in Python",
    defaultLang: "python",
    iconName: "Code2",
    isCseCore: true,
  },
  {
    id: "devops",
    name: "DevOps",
    role: "DevOps Engineer",
    category: "CSE & IT Domains",
    tech: "Docker, Kubernetes, CI/CD, Terraform, Linux",
    description: "CI/CD pipelines, Docker, Kubernetes, Terraform & infrastructure automation",
    defaultLang: "python",
    iconName: "Server",
    isCseCore: true,
  },
  {
    id: "aws",
    name: "AWS",
    role: "AWS Cloud Architect",
    category: "CSE & IT Domains",
    tech: "AWS EC2, S3, Lambda, VPC, DynamoDB, IAM",
    description: "EC2, S3, Lambda, VPC, DynamoDB, IAM & cloud solutions design",
    defaultLang: "python",
    iconName: "Cloud",
    isCseCore: true,
  },
  {
    id: "gen-agentic-ai",
    name: "AI (Generative & Agentic)",
    role: "Generative AI Engineer",
    category: "CSE & IT Domains",
    tech: "LLMs, LangChain, RAG, LlamaIndex, AI Agents, Vector DBs",
    description: "LLMs, prompt engineering, RAG, LangChain, vector DBs & autonomous agents",
    defaultLang: "python",
    iconName: "Sparkles",
    isCseCore: true,
  },
  {
    id: "mobile-dev",
    name: "Mobile App Development",
    role: "Mobile App Engineer",
    category: "CSE & IT Domains",
    tech: "Flutter, React Native, iOS, Android, Dart",
    description: "Cross-platform mobile apps, Flutter, React Native & mobile state",
    defaultLang: "javascript",
    iconName: "Smartphone",
    isCseCore: true,
  },

  // ── Advanced CS Fundamentals ──
  {
    id: "dsa",
    name: "Data Structures & Algorithms (General)",
    role: "Software Engineer",
    category: "CSE & IT Domains",
    tech: "Arrays, Trees, Graphs, DP, C++, Java",
    description: "Arrays, Trees, Graphs, DP & Algorithmic Problem Solving",
    defaultLang: "cpp",
    iconName: "Code2",
  },
  {
    id: "system-design",
    name: "System Design & Scalability",
    role: "Systems Architect",
    category: "CSE & IT Domains",
    tech: "Distributed Systems, Load Balancers, Sharding, Caching",
    description: "Distributed Systems, Load Balancers, Sharding & Caching",
    defaultLang: "javascript",
    iconName: "Cpu",
  },
  {
    id: "dbms",
    name: "SQL, NoSQL & Data Modeling",
    role: "Database Engineer",
    category: "CSE & IT Domains",
    tech: "Queries, Indexing, Transactions, Postgres, MongoDB",
    description: "Queries, Indexing, Transactions, Postgres & MongoDB",
    defaultLang: "javascript",
    iconName: "Database",
  },
  {
    id: "os-networking",
    name: "OS, Concurrency & Networking",
    role: "Systems Engineer",
    category: "CSE & IT Domains",
    tech: "Multithreading, Memory Locks, Sockets, TCP/IP",
    description: "Multithreading, Memory Locks, Sockets & TCP/IP Protocol",
    defaultLang: "cpp",
    iconName: "Terminal",
  },
  {
    id: "microservices",
    name: "Microservices & Message Queues",
    role: "Backend Engineer",
    category: "CSE & IT Domains",
    tech: "Event-Driven Architecture, Kafka, RabbitMQ, gRPC",
    description: "Event-Driven Systems, Kafka, RabbitMQ & gRPC",
    defaultLang: "javascript",
    iconName: "Layers",
  },

  // ── Design & Creative ──
  {
    id: "ui-ux",
    name: "UI/UX & Product Design",
    role: "UI / UX Designer",
    category: "Design & Creative",
    tech: "Figma, User Research, Wireframing, Prototyping, Design Systems",
    description: "User research, wireframing, Figma components, usability testing & visual design systems",
    defaultLang: "javascript",
    iconName: "Palette",
  },
  {
    id: "graphic-design",
    name: "Graphic & Brand Visual Design",
    role: "Graphic Designer",
    category: "Design & Creative",
    tech: "Photoshop, Illustrator, Visual Identity, Typography, Color Theory",
    description: "Brand identities, typography hierarchy, marketing visuals, and vector illustrations",
    defaultLang: "javascript",
    iconName: "PenTool",
  },

  // ── Management, Business & Finance ──
  {
    id: "product-management",
    name: "Product Management",
    role: "Product Manager",
    category: "Management & Business",
    tech: "PRD Writing, Agile/Scrum, User Personas, Product Roadmaps, A/B Testing",
    description: "Product discovery, roadmapping, backlog grooming, metric prioritization & cross-functional leadership",
    defaultLang: "javascript",
    iconName: "Briefcase",
  },
  {
    id: "finance",
    name: "Finance & Financial Modeling",
    role: "Financial Analyst",
    category: "Management & Business",
    tech: "DCF Valuation, Financial Statement Analysis, Capital Budgeting, Excel",
    description: "Corporate finance, three-statement modeling, ratio analysis, and forecasting",
    defaultLang: "python",
    iconName: "DollarSign",
  },
  {
    id: "investment-banking",
    name: "Investment Banking & Advisory",
    role: "Investment Banking Analyst",
    category: "Management & Business",
    tech: "M&A Advisory, LBO Modeling, Pitch Books, Equity Underwriting",
    description: "M&A deal mechanics, valuation multiples, due diligence & pitch deck preparation",
    defaultLang: "python",
    iconName: "Briefcase",
  },
  {
    id: "stock-market",
    name: "Equity Research & Stock Market",
    role: "Equity Research Analyst",
    category: "Management & Business",
    tech: "Technical Analysis, F&O Derivatives, RSI/MACD, Fundamental Research",
    description: "Market microstructure, risk hedging, equities valuation, and portfolio management",
    defaultLang: "python",
    iconName: "TrendingUp",
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing & Growth",
    role: "Digital Marketing Specialist",
    category: "Management & Business",
    tech: "SEO, SEM, Meta/Google Ads, CAC/LTV, Funnel Optimization",
    description: "Growth loops, paid ad optimization, SEO strategies, and conversion tracking",
    defaultLang: "javascript",
    iconName: "Megaphone",
  },
  {
    id: "hrm",
    name: "Human Resource Management (HRM)",
    role: "HR & Talent Acquisition Manager",
    category: "Management & Business",
    tech: "Talent Sourcing, Competency Interviews, Performance Appraisals, Labor Laws",
    description: "Strategic talent acquisition, employee retention, organizational design, and labor compliance",
    defaultLang: "javascript",
    iconName: "Users",
  },
  {
    id: "supply-chain",
    name: "Operations & Supply Chain",
    role: "Operations & Supply Chain Manager",
    category: "Management & Business",
    tech: "Inventory EOQ/JIT, Bullwhip Effect, Logistics, Procurement, Six Sigma",
    description: "Supply chain resilience, vendor management, warehouse automation, and operations planning",
    defaultLang: "python",
    iconName: "Truck",
  },
  {
    id: "startup-entrepreneurship",
    name: "Startup & Entrepreneurship",
    role: "Startup Founder & Entrepreneur",
    category: "Management & Business",
    tech: "MVP Validation, Pitch Decks, Cap Tables, Runway Management, Product-Market Fit",
    description: "Venture fundraising, go-to-market execution, early customer acquisition, and business model canvas",
    defaultLang: "javascript",
    iconName: "Rocket",
  },
  {
    id: "sales-business-dev",
    name: "Sales & Business Development",
    role: "Business Development Executive (BDE)",
    category: "Management & Business",
    tech: "B2B Negotiation, Lead Qualification, CRM Pipeline, Consultative Selling",
    description: "Cold outreach, high-value client closing, account planning, and relationship management",
    defaultLang: "javascript",
    iconName: "TrendingUp",
  },

  // ── Core Engineering (Mechanical, Civil, Automotive) ──
  {
    id: "autocad-mechanical",
    name: "Mechanical Design & AutoCAD",
    role: "Mechanical Design Engineer",
    category: "Core Engineering",
    tech: "AutoCAD 2D/3D, SolidWorks, GD&T, FEA Simulation, Tolerance Stack-up",
    description: "Mechanical component drafting, geometric dimensioning, finite element analysis & material selection",
    defaultLang: "cpp",
    iconName: "Compass",
  },
  {
    id: "hev",
    name: "Hybrid & Electric Vehicles (HEV)",
    role: "EV Powertrain Engineer",
    category: "Core Engineering",
    tech: "Electric Powertrain, Battery Management Systems (BMS), Regenerative Braking, Motor Inverters",
    description: "EV motor architectures, thermal runaway mitigation, state-of-charge algorithms, and high-voltage safety",
    defaultLang: "cpp",
    iconName: "Zap",
  },
  {
    id: "car-designing",
    name: "Car Designing & Automotive Engineering",
    role: "Automotive Designer",
    category: "Core Engineering",
    tech: "Aerodynamic Drag, Chassis Dynamics, NVH, Crashworthiness, Vehicle Packaging",
    description: "Body-in-white structures, vehicle styling aesthetics, suspension tuning & safety standards",
    defaultLang: "cpp",
    iconName: "Car",
  },
  {
    id: "civil-project-management",
    name: "Civil Site & Project Engineering",
    role: "Civil Project Engineer",
    category: "Core Engineering",
    tech: "Structural BIM, Quantity Surveying, Bar Bending Schedules, CPM/PERT Planning",
    description: "Concrete mix design, soil mechanics, structural foundation analysis & high-rise project planning",
    defaultLang: "cpp",
    iconName: "HardHat",
  },
  {
    id: "mech-product-management",
    name: "Product Management (Mechanical)",
    role: "Mechanical Product Engineer",
    category: "Core Engineering",
    tech: "Design for Manufacturing (DFM), Design for Assembly (DFA), Prototyping, CAD/CAM",
    description: "Manufacturing feasibility, tooling cost estimation, injection molding & rapid prototyping",
    defaultLang: "cpp",
    iconName: "Layers",
  },

  // ── ECE & Robotics ──
  {
    id: "embedded-systems",
    name: "Embedded Systems & Microcontrollers",
    role: "Embedded Systems Engineer",
    category: "ECE & Robotics",
    tech: "ARM Cortex, C/C++, FreeRTOS, Firmware, Timers, I2C/SPI/UART",
    description: "Bare-metal programming, memory-mapped I/O, RTOS tasks, and low-level peripheral drivers",
    defaultLang: "cpp",
    iconName: "Cpu",
  },
  {
    id: "vlsi",
    name: "VLSI & Digital Electronics",
    role: "VLSI Design Engineer",
    category: "ECE & Robotics",
    tech: "Verilog HDL, CMOS Inverters, Static Timing Analysis, FPGAs, Logic Synthesis",
    description: "RTL design, setup/hold slack calculations, ASIC flow, and digital combinational circuits",
    defaultLang: "cpp",
    iconName: "Layers",
  },
  {
    id: "robotics",
    name: "Robotics & Automation (ROS)",
    role: "Robotics Engineer",
    category: "ECE & Robotics",
    tech: "ROS/ROS2, Forward/Inverse Kinematics, SLAM, PID Controllers, Actuators",
    description: "Manipulator dynamics, sensor fusion (IMU/LiDAR), path planning (A*/RRT) & robot state estimation",
    defaultLang: "cpp",
    iconName: "Bot",
  },
  {
    id: "drone-engineering",
    name: "Drone Engineering & UAVs",
    role: "Drone Flight Systems Engineer",
    category: "ECE & Robotics",
    tech: "PX4/ArduPilot, Quadcopter Flight Dynamics, ESCs, Telemetry, BLDC Motors",
    description: "Avionics integration, multirotor PID stabilization, autonomous waypoint navigation & payload sizing",
    defaultLang: "cpp",
    iconName: "Navigation",
  },
  {
    id: "iot",
    name: "IoT & Sensor Networks",
    role: "IoT Specialist",
    category: "ECE & Robotics",
    tech: "ESP32, MQTT, CoAP, LoRaWAN, Sensor Interfacing, Edge Computing",
    description: "Low-power wireless nodes, publish-subscribe telemetry, edge filtering & cloud gateway integration",
    defaultLang: "cpp",
    iconName: "Cpu",
  },

  // ── Healthcare, Pharma & Life Sciences ──
  {
    id: "clinical-research",
    name: "Clinical Trial & Research (Pharma)",
    role: "Clinical Research Associate (CRA)",
    category: "Healthcare & Pharma",
    tech: "Phases I-IV Protocols, Good Clinical Practice (GCP), Pharmacovigilance, FDA Audits",
    description: "Clinical protocol monitoring, patient safety reporting, informed consent audits & trial documentation",
    defaultLang: "python",
    iconName: "TestTube",
  },
  {
    id: "medical-coding",
    name: "Medical Coding (Pharma/Healthcare)",
    role: "Medical Coding Specialist",
    category: "Healthcare & Pharma",
    tech: "ICD-10-CM, CPT, HCPCS Level II, HIPAA Compliance, Revenue Cycle Management",
    description: "Diagnostic coding, clinical documentation improvement, billing guidelines & audit integrity",
    defaultLang: "python",
    iconName: "FileSpreadsheet",
  },
  {
    id: "genetic-engineering",
    name: "Genetic Engineering & Biotech",
    role: "Genetic Engineer",
    category: "Healthcare & Pharma",
    tech: "CRISPR-Cas9, Recombinant DNA, PCR Amplification, Plasmid Vectors, Gene Sequencing",
    description: "Molecular biology assays, transgenic constructs, cell culture protocols & bioinformatics analysis",
    defaultLang: "python",
    iconName: "Dna",
  },
  {
    id: "psychology",
    name: "Health Psychology & Behavioral Science",
    role: "Health Psychologist",
    category: "Healthcare & Pharma",
    tech: "CBT Assessment, Neuropsychology, Stress Biomarkers, Behavioral Intervention",
    description: "Psychological evaluation methodologies, mental health interventions & psychometric testing",
    defaultLang: "python",
    iconName: "HeartPulse",
  },
  {
    id: "nanotechnology",
    name: "Nanotechnology (Pharma/Materials)",
    role: "Nanotechnology Researcher",
    category: "Healthcare & Pharma",
    tech: "Nanoparticle Synthesis, Targeted Drug Delivery, Carbon Nanotubes, SEM/TEM Analysis",
    description: "Nano-carrier encapsulation, surface functionalization, biocompatibility testing & material physics",
    defaultLang: "python",
    iconName: "Atom",
  },
];
